const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = {
  resolver: {
    /**
     * A list of directories to exclude from Metro's file watcher.
     * This is useful for excluding temporary build directories, which can cause
     * the watcher to crash.
     */
    blockList: [
      // Ignore the .cxx directory, which is generated by the Android NDK build.
      /android\/app\/\.cxx\/.*/,
      // Ignore the build folder, which is generated by the Android build.
      /android\/app\/build\/.*/,
    ],
  },
};

module.exports = mergeConfig(getDefaultConfig(__dirname), config);
